### ISSUE TITLE
IPsec monitor problems

### ISSUE THREAD

**Issue by blackzombie87** [bashclub/check-opnsense#1]
Hi,

thank you very much for your agent!

When monitoring IPsec connections it fails with a Traceback:

`Traceback (most recent call last):
  File "/usr/local/etc/rc.syshook.d/start/99-checkmk_agent", line 104, in do_checks
    _lines += getattr(self,_check)()
  File "/usr/local/etc/rc.syshook.d/start/99-checkmk_agent", line 553, in checklocal_ipsec
    _childsas = next(_childsas)
StopIteration`

Maybe it's caused by a down IPsec tunnel, here is the corresponding output from /usr/local/opnsense/scripts/ipsec/list_status.py:

`"con5":{"local-addrs":"xxx.xxx.xxx.xxx","remote-addrs":"xxx.xxx.xx,0.0.0.0\/0,::\/0","children":{"con5":{"mode":"TUNNEL","rekey_time":"28260","rekey_bytes":"0","rekey_packets":"0","dpd_action":"restart","close_action":"clear","local-ts":["0.0.0.0\/0"],"remote-ts":["0.0.0.0\/0"]}},"local-id":"xxx.xxx.xxx.xxx","remote-id":"xxx.xxx.xx","version":"IKEv2","sas":[],"routed":true,"local-class":"pre-shared key","remote-class":"pre-shared key"}`

Can you have a look please?

Thanks,
Christian

**Comment by thorstenspille** [comment]
Please check testing branch, should be fixed with https://github.com/bashclub/check-opnsense/commit/e1c5d1a121059f61eaab5db6954f778e59b41693
