### ISSUE TITLE
SMART check plugin?

### ISSUE THREAD

**Issue by mapietru** [bashclub/check-opnsense#11]
Hello,

I am missing the basic smart check within the checks, but from what I see in the agent feedback, there seems to be a very good and detailed custom check included.

![image](https://user-images.githubusercontent.com/87319110/175477454-63ce7e7d-c7b9-4cef-a699-6d1befe281c5.png)

I guess to collect this info with check_mk server I need to have the plugin, right? We can I find it?

And thumbs up for the great work!

Br,
Markus

**Comment by mapietru** [comment]
This section is still present in v0.96 and looks more than interessting for me, any further information about a plugin (mkp) to get this working?

Br,
Markus

**Comment by sibelle-labs** [comment]
lock at https://nc.cloudistboese.de/index.php/s/EQ5xqXsmoWQe2S8

**Comment by thorstenspille** [comment]
Please check testing branch, should be fixed with https://github.com/bashclub/check-opnsense/commit/e1c5d1a121059f61eaab5db6954f778e59b41693
