### ISSUE TITLE
filter rule.

### ISSUE THREAD

**Issue by burghy86** [bashclub/check-opnsense#16]
hi. i have:
enable ssh
connect with putty
type 8 to open shell
type a command:
fetch -o /usr/local/etc/rc.syshook.d/start/99-checkmk_agent https://github.com/bashclub/check-opnsense/raw/main/opnsense_checkmk_agent.py
chmod +x /usr/local/etc/rc.syshook.d/start/99-checkmk_agent
/usr/local/etc/rc.syshook.d/start/99-checkmk_agent

and all is good.

but the rule for open 6556 on wan not work.
someone explain me how to make this rule?

I created a rule like this in nat / port forward for accept request only for my checkmk public ip server:

https://i.imgur.com/hBcE1tE.png

but in a remote check mk server the test agent go to timeout

https://i.imgur.com/8Vi67OL.png

**Comment by sibelle-labs** [comment]
Hi.

running and listening ??? try 
```
netstat -ln -4 |grep 6556
tcp4       0      0 192.168.10.1.6556      192.168.10.5.49116       TIME_WAIT
```
or 
```
telnet 127.0.0.1 6556 # for test if reply ...
```
are you sure you want to reach the opnsense-checkmk from the internet?
For firewall configuration help, the best place is forum.opnsense.org

cheers,
