### ISSUE TITLE
nginx check: Zones vanish after reboot or nginx restart until first call of the site

### ISSUE THREAD

**Issue by thorstenspille** [bashclub/check-opnsense#18]
Service is only shown, if runtime logs or metrics for specific Zone available?

**Comment by mapietru** [comment]
indeed, recognized this as well.

**Comment by thorstenspille** [comment]
Please check testing branch, should be fixed with https://github.com/bashclub/check-opnsense/commit/e1c5d1a121059f61eaab5db6954f778e59b41693
