### ISSUE TITLE
IPSec Monitoring

### ISSUE THREAD

**Issue by danielka60** [bashclub/check-opnsense#19]
Hello,

i found a Problem within the IPSec Monitoring. I have 92 Tunnels (phase 1 and 2), but only 2 tunnels are shown in checkmk.

I found out that the 2 Tunnels, that are displayed only have 1 phase 2 entry, all others have more then 1.

Maybe this is the problem

Thank you!
Daniel

**Comment by thorstenspille** [comment]
Please check testing branch, should be fixed with https://github.com/bashclub/check-opnsense/commit/e1c5d1a121059f61eaab5db6954f778e59b41693
