### ISSUE TITLE
Service "WireGuard VPN" shows CRIT, with installed kmod

### ISSUE THREAD

**Issue by markus-gitdev** [bashclub/check-opnsense#20]
Hi,

The Service "WireGuard VPN" shows up as not running (which it also does in the WebUI), when the WireGuard kmod is installed.
Is there a way to fix this, since the service is OK? Either directly in the check script, or in WATO on the checkmk-instance?

Thank you!

**Comment by thorstenspille** [comment]
Please check testing branch, should be fixed with https://github.com/bashclub/check-opnsense/commit/e1c5d1a121059f61eaab5db6954f778e59b41693
