### ISSUE TITLE
Absturz in Check MK Vers. 2.1.0p19

### ISSUE THREAD

**Issue by ascentler** [bashclub/check-opnsense#25]
Hallo,
Check MK stürzt beim Versuch das Plugin zu erkunden ab.
Der Absturzbericht beginnt mit:
ValueError (Invalid line in agent section <<<local>>>. Reason: Invalid performance data: ''.  First offending line: "2 "OpenVPN Server: rw_OpenVPN_Server" connections_ssl_vpn=0;;63|expire
Ist da was bekannt?
Werden weitere Informationen benötigt?

**Comment by thorstenspille** [comment]
Please check testing branch, should be fixed with https://github.com/bashclub/check-opnsense/commit/e1c5d1a121059f61eaab5db6954f778e59b41693

**Comment by ascentler** [comment]
Nein, der Fehler besteht immer noch:
![Screenshot 2023-04-17 113605](https://user-images.githubusercontent.com/122615278/232447532-83365ad5-8a40-4755-ba43-e8969f819125.jpg)

Check_MK Discovery

check failed - please submit a crash report! (Crash-ID: 4c1cf6ee-dcfe-11ed-8d94-02cdc69cee71)

ValueError (Invalid line in agent section <<<local>>>. Reason: Invalid performance data: ''.  First offending line: "2 "OpenVPN Server: rw_OpenVPN_Server" connections_ssl_vpn=0;;63|expiredays=3542|if_in_octets=0|if_out_octets=0| Server down Port:1195/UDP \nCert Expire: 27.12.2032")

**Comment by thorstenspille** [comment]
@ascentler your agent version is still 0.99.2, please update and check again.
