### ISSUE TITLE
Fehler bei Development Version der OPNSense Firmware

### ISSUE THREAD

**Issue by TomTom68** [bashclub/check-opnsense#29]
Wenn eine Development-Version von OPNSense benutzt wird, dann läuft das Python Script leider auf einen Fehler beim Auslesen der Firmware Version. In dieser ist ein Buchstabe vor dem Tiefstrich enthalten, welcher leider den korrekten Lauf des ansonsten sehr tollen Scriptes verhindert. Das Script liefert in diesem Fall über den Port 6556 überhaupt kein Ergebnis zurück.

**Comment by thorstenspille** [comment]
Please check testing branch, should be fixed with https://github.com/bashclub/check-opnsense/commit/e1c5d1a121059f61eaab5db6954f778e59b41693
