### ISSUE TITLE
Not working with dynamic DNS

### ISSUE THREAD

**Issue by cpzengel** [bashclub/check-opnsense#9]
After new IP Address the IPSEC Item vanishes and a new Service will be found.
Perhaps better to name the IPSEC Service with the Description, if available?

**Comment by sibelle-labs** [comment]
I think this can be solved on the checkmk side.
Network Monitoring with Checkmk: 3 rules to rule them all (Interface: by Alias/by Description)
see https://checkmk.com/blog/network-monitoring-with-checkmk-2-0

**Comment by thorstenspille** [comment]
Please check testing branch, should be fixed with https://github.com/bashclub/check-opnsense/commit/e1c5d1a121059f61eaab5db6954f778e59b41693
